### ISSUE TITLE
explore the possibility of using rdf:list, rdf:seq, etc. to generate less diff

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/xmltoldmigration#9]
If we use git, it's important that we can serialize the same document twice without generating the enormous amount of diff we currently do, for log entries and everything with multiple unordered property values

**Comment by xristy** [comment]
I agree. Do either of `rdf:list` or `rdf:seq` map to json arrays? Where do you have in mind using these?

**Comment by xristy** [comment]
The diffs for the bdrc.owl file seem reasonable presumably due to sorting the contents and using other formatting conventions consistently.

We had at one point discussed the idea of something like a _bdrc github service_ that would be responsible for

- normalizing the file to be committed
- checking authorizations to determine if the implied PR can be automatic or needs manual review

If there was such a service then it would make the diff'ing issue dependent only on the normalization procedures of the service and independent of what sort of editing tool was used on the submitted file(s).
